# Generated by Django 3.2.18 on 2023-03-27 17:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Ф.И.О.')),
                ('company', models.CharField(max_length=256, verbose_name='Компания')),
                ('department', models.CharField(choices=[('PR', 'PR и маркетинг'), ('RS', 'Риски и безопасность'), ('OTH', 'Другое')], max_length=3, verbose_name='Подразделение')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('pd_agreement', models.BooleanField(verbose_name='Согласен на обработку ПД')),
                ('in_mailing_list', models.BooleanField(verbose_name='Согласен на рассылку')),
            ],
        ),
    ]
